### ISSUE TITLE
Not working in the latest version (1.0.0-rc.10)

### ISSUE THREAD

**Issue by javinba** [QC2168/vite-plugin-vitepress-auto-sidebar#11]
Hello!

First of all thanks for the contribution.

I'm trying to use the plugin from version `1.0.0-rc.10` and I'm encountering with
```
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vitepress@1.0.0-rc.10
npm ERR! node_modules/vitepress
npm ERR! vitepress@"^1.0.0-rc.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vitepress@"1.0.0-alpha.49" from vite-plugin-vitepress-auto-sidebar@1.6.0
```

Could you update it so that it can be used in the latest versions of vitepress?

Thanks, best regards.

**Comment by QC2168** [comment]
I tried the plugin, it is working, can you provide a demo warehouse?

**Comment by shimizu1995** [comment]
Hello!

First, I wanted to say that this is a fantastic plugin. Thank you for developing it!

I noticed an issue regarding `peerDependencies`. Maybe changing it from:

    "vitepress": "1.0.0-alpha.49"

to:

    "vitepress": "^1.0.0"

will fix it.

**Comment by QC2168** [comment]
Thank you for your reminder! I have removed duplicate deps and updated the vite version. @shimizu1995
