### ISSUE TITLE
当配置三级路径的时候，如何不显示上一层级的文件夹

### ISSUE THREAD

**Issue by yecss** [QC2168/vite-plugin-vitepress-auto-sidebar#12]
我的侧边栏
![Snipaste_2023-10-10_21-58-02](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/32784471/4cf808fa-4ad9-4f14-9178-cd1534b1cb7b)

我的文件结构
![Snipaste_2023-10-10_21-58-50](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/32784471/30a0fb26-9c8e-4b59-84d3-21956d49c2d2)

我的导航栏配置
`{
        text: 'web前端',
        items: [
          { text: 'HTML', link: '/web前端/HTML/1、语义结构.md' },
        ],
      },`

**Comment by QC2168** [comment]
您可以通过`sideBarResolved`这个钩子把你不需要的子项去除
