### ISSUE TITLE
请问如何控制某个文件夹下目录的是否折叠，以及折叠层级呢

### ISSUE THREAD

**Issue by zhaozhiliao** [QC2168/vite-plugin-vitepress-auto-sidebar#13]

**Comment by QC2168** [comment]
您可以使用官方的[collapsible-sidebar-groups](https://vitepress.dev/reference/default-theme-sidebar#collapsible-sidebar-groups)字段来实现这个需求

**Comment by QC2168** [comment]
@zhaozhiliao 利用`sideBarResolved`/`sideBarItemsResolved`钩子进行设置
