### ISSUE TITLE
rc.25 不匹配哦，没有侧边栏

### ISSUE THREAD

**Issue by hxer520** [QC2168/vite-plugin-vitepress-auto-sidebar#14]
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/12802662/2982a3f6-bd48-429a-ae8e-63b887516297)

**Comment by QC2168** [comment]
@hxer520  您好，我这边试了下最新的`vitepress`版本，没有复现您反馈的这个问题，可以提供最小`DEMO`吗
```json
"devDependencies": {
  "vitepress": "1.0.0-rc.25"
}
```

**Comment by QC2168** [comment]
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/82024018/9a034c9f-1d9e-41c0-a2f7-7f0759b13dde)

**Comment by NARUDESIGNS** [comment]
I have this problem as well. No sidebar was created.
Do you think it requires the latest version of Vitepress to work?
@QC2168

**Comment by QC2168** [comment]
> I have this problem as well. No sidebar was created. Do you think it requires the latest version of Vitepress to work? @QC2168

@NARUDESIGNS  I am using the latest version(`"vitepress": "1.0.0-rc.25"`) of vitepress and it is working

Can you provide mini repo for testing?

**Comment by NARUDESIGNS** [comment]
I will make a small repo later but also you can test it with Vitepress version 1.0.0-rc.20 and see if it works fine.
That is the Vitepress version I use @QC2168

**Comment by QC2168** [comment]
@NARUDESIGNS  I will vitepress change to `1.0.0-rc.20`， it work normally
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/82024018/0f701a77-dfa5-44a0-b651-b750d3ef8b87)
