### ISSUE TITLE
vite最新版本会有提示错误

### ISSUE THREAD

**Issue by zhaozhiliao** [QC2168/vite-plugin-vitepress-auto-sidebar#15]
<img width="722" alt="Snipaste_2023-12-05_10-42-12" src="https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/51565169/1e1c5762-c1dc-4560-a8a2-f6b392026f5b">
好像不支持vite最新版本

**Comment by QC2168** [comment]
@zhaozhiliao 你使用的插件版本是最新的吗？我看了`vite.config.plugins`类型是与插件一致的

**Comment by zhaozhiliao** [comment]
> @zhaozhiliao 你使用的插件版本是最新的吗？我看了`vite.config.plugins`类型是与插件一致的

是最新的，插件可以用。就是这个提示有点困惑
