### ISSUE TITLE
请问 beforeCreateSideBarItems 如何进行排序呢？

### ISSUE THREAD

**Issue by sunpm** [QC2168/vite-plugin-vitepress-auto-sidebar#16]
大佬有没有实例方法

**Comment by QC2168** [comment]
可以使用[Array,sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)进行排序操作

**Comment by sunpm** [comment]
好的，我研究一下，js 基础有点差，感谢您的解答
