### ISSUE TITLE
vitepress@1.0.0-rc.44无法使用

### ISSUE THREAD

**Issue by GuoDong999** [QC2168/vite-plugin-vitepress-auto-sidebar#20]
![Screenshot_2024-03-02-18-22-23-099_com.microsoft.rdc.androidx.jpg](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/24713539/887cc8a9-7d4c-4c57-b52d-b23cd6e217f3)

**Comment by tennisteam** [comment]
Use pnpm instead of npm

**Comment by CvdL-UM** [comment]
> Use pnpm instead of npm

Pnpm gives me the same error `unmet peer vitepress@1.0.0-rc.33: found 1.0.0-rc.45`

**Comment by QC2168** [comment]
Hi, Please update the latest version 1.6.3 and try again
