### ISSUE TITLE
建议: 反向添加

### ISSUE THREAD

**Issue by fr1g** [QC2168/vite-plugin-vitepress-auto-sidebar#22]
可不可以添加可选的工作模式, 在服务器启动时检查config然后依据它在sidebar指向的文件目录下创建文件? 这将在一定程度上简化文件创建流程
*但是不要覆盖现有文件, 改名可选不删除对应的旧文件(留给用户整理文件时候自己删除)*

**Comment by fr1g** [comment]
如果能反过来添加文件那甚至只需要改配置文件，不再需要切换到文件资源管理器/vscode侧边栏来新建、改名… 有的时候就是觉得扣键盘比手点来得快Отправлено с iPhone29 апр. 2024 г., в 20:32, _island ***@***.***> написал(а):﻿
这个插件是用于生成侧边栏数据的，生成文件这个场景不多吧😶

**Comment by QC2168** [comment]
但是创建的内容是空的，也没有什么帮助？

**Comment by fr1g** [comment]
难道还想接入ai帮写吗，肯定是空的啊Отправлено с iPhone30 апр. 2024 г., в 19:40, _island ***@***.***> написал(а):﻿
但是创建的内容是空的，也没有什么帮助？

**Comment by QC2168** [comment]
考虑到应用场景较少，暂不计划添加该功能
