### ISSUE TITLE
左边侧边栏是空的

### ISSUE THREAD

**Issue by weited** [QC2168/vite-plugin-vitepress-auto-sidebar#25]
大佬你好, 我安装之后, 左边侧边栏是空的, 是不是我配置错了什么

系统: Win11
Node: 18, 20 多个版本
pnpm: 8.15.6,

```
import { defineConfig } from "vitepress";
import AutoSidebar from "vite-plugin-vitepress-auto-sidebar";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "xxx",
  description: "Documentation",
  // cleanUrls: true,
  vite: {
    plugins: [
      AutoSidebar({
        collapsed: false,
      }),
    ],
  },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: "Home", link: "/" },
      { text: "Examples", link: "/markdown-examples" },
    ],
},
})
```
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/34746692/24deeda5-5d79-4397-a964-0ba723c4f33a)

**Comment by QC2168** [comment]
文件目录是怎么样的？可以提供最小demo吗

**Comment by qintang** [comment]
.
├── docs
│   ├── 2022任�\212�summary.md
│   ├── README.md
│   ├── api-examples.md
│   ├── he
│   │   └── hello.md
│   ├── index.md
│   ├── markdown-examples.md
│   └── onesh.md
├── package-lock.json
├── package.json
├── upload_file.ddmc.sh
└── yarn.lock

2 directories, 11 files
