### ISSUE TITLE
使用后，也不是完全没有生成，就是只生成一部分。

### ISSUE THREAD

**Issue by ClownZyk** [QC2168/vite-plugin-vitepress-auto-sidebar#29]
![微信截图_20240429105702](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/24559191/711a0577-dfe7-4cb4-aed9-5f8693bcc29b)

![微信截图_20240429105851](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/24559191/0d4807cf-3d3b-46f7-a3fd-688ac68743db)

目录结构是1图，但是生成的sidebar只有node文件夹里的两个路径，是命名问题吗？
![微信截图_20240429110031](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/24559191/adf225a1-29e9-4b97-85e2-f0a7991d737f)
![微信截图_20240429110107](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/24559191/66e557ad-f94d-4909-aac2-6cdab2fd53f7)

**Comment by QC2168** [comment]
@ClownZyk 可以提供下最小仓库demo吗

**Comment by QC2168** [comment]
我先关闭问题了，后续如有提供在开启吧
