### ISSUE TITLE
请教一下如何实现官网这种分组布局？

### ISSUE THREAD

**Issue by dlzmoe** [QC2168/vite-plugin-vitepress-auto-sidebar#30]
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/65840178/e5a729b3-d921-4101-9995-9001b4a6933d)

如图，下方是我本地结构，似乎无法实现分组，只有层级关系
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/65840178/ce4ee93b-7b93-43d7-a93c-073c8bd22d68)

**Comment by QC2168** [comment]
可以使用`collapsed`属性
