### ISSUE TITLE
希望侧边栏的标题支持YAML 格式的 frontmatter，而不是读取markdown中的 # title

### ISSUE THREAD

**Issue by a1burning** [QC2168/vite-plugin-vitepress-auto-sidebar#33]
https://vitepress.dev/zh/guide/markdown#frontmatter

如果页面中配置了

---
title: Less编译
tags: 
  - Less
prev: ./01.md
next: ./03.md
sidebarDepth: 5
---

希望可以从title中读取标题当侧边栏的标题，而不是# title，因为bash中的注释什么的，和这个格式一样。
我使用了插件之后有了莫名其妙的标题。

**Comment by QC2168** [comment]
好，我看一下

**Comment by QC2168** [comment]
已经添加，请更新`1.7.0`
