### ISSUE TITLE
能否提供插入的路径

### ISSUE THREAD

**Issue by nicopcat** [QC2168/vite-plugin-vitepress-auto-sidebar#34]
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/21167750/0da1a6f5-fb2c-4cd7-a762-f2b1cefcf8e4)

主要是因为开启 i18n 之后会有多个配置路径

**Comment by QC2168** [comment]
配置下入口文件是否能够解决？
