### ISSUE TITLE
新增一个文件后，自动重启失败

### ISSUE THREAD

**Issue by struggle-fish** [QC2168/vite-plugin-vitepress-auto-sidebar#37]
<img width="595" alt="image" src="https://github.com/user-attachments/assets/ef15e2ce-76d9-4a4b-9a92-4d9f1c72b891">

<img width="530" alt="image" src="https://github.com/user-attachments/assets/61003903-cef6-4576-8190-be14c907be34">

<img width="530" alt="image" src="https://github.com/user-attachments/assets/66b29951-66cc-42cc-b2f3-e10aac001f59">

新增一个测试文件，然后提示重启了，但没有成功，刷新页面后没变化

**Comment by QC2168** [comment]
我这边试了下。添加和删除 无法复现该问题，可以提供Demo吗

**Comment by struggle-fish** [comment]
> 我这边试了下。添加和删除 无法复现该问题，可以提供Demo吗

https://github.com/struggle-fish/myBlog

是这个

**Comment by liuliangsir** [comment]
@struggle-fish you might could try [vitepress-auto-configure-nav-sidebar](https://github.com/w3ctech-editorial-department/vitepress-auto-configure-nav-sidebar).

**Comment by QC2168** [comment]
> > 我这边试了下。添加和删除 无法复现该问题，可以提供Demo吗
> 
> https://github.com/struggle-fish/myBlog
> 
> 是这个

好，我试试

**Comment by QC2168** [comment]
这是`vitepress`的一个`bug`，暂时的解决方案是在`config.mts`中关闭`provider: 'local'` @struggle-fish

**Comment by struggle-fish** [comment]
非常感谢
