### ISSUE TITLE
example 测试项目的vitePress 版本需要升级，现在版本的运行案例后会报错

### ISSUE THREAD

**Issue by wcySpring** [QC2168/vite-plugin-vitepress-auto-sidebar#4]
example 测试项目的vitePress 版本需要升级，现在版本的运行案例后会报错
![image](https://user-images.githubusercontent.com/128951289/236233090-07052a67-c01b-4a01-9bc4-c77e068bd5bb.png)
建议升级到最新没有这个错误问题

**Comment by QC2168** [comment]
好，我更新一下Demo版本，感谢！❤
