### ISSUE TITLE
增加两个功能：指定文章前缀让文章可以排序 / 菜单增加了折叠配置

### ISSUE THREAD

**Issue by wcySpring** [QC2168/vite-plugin-vitepress-auto-sidebar#5]
你好，我在使用的过程中在我的本地案例中增加了
* 指定文章前缀让文章可以排序 
*  菜单增加了折叠配置
**两个功能，如果可以的话 我很想将这两个功能合并过来**

###  **菜单增加了折叠配置**
![image](https://user-images.githubusercontent.com/128951289/236234510-f805eadb-e543-46ae-a220-d083de211ddc.png)

### **文章可以排序** 
![image](https://user-images.githubusercontent.com/128951289/236234700-05e64393-bb65-4469-93b2-308ff2c2570f.png)
![image](https://user-images.githubusercontent.com/128951289/236234922-68a0f713-17ad-41a3-bed3-b6045a1dcbec.png)

### **代码上我增加了两个配置**
![image](https://user-images.githubusercontent.com/128951289/236234864-bfb2c024-58b7-43a9-9a1e-14fc3eaab0f5.png)

**Comment by wcySpring** [comment]
如果可以的话 我可以将我的代码合并过来

**Comment by QC2168** [comment]
@wcySpring 哈喽 兄弟，可以提交个Pr，没问题的话我这边合并一下

**Comment by QC2168** [comment]
有选项更变时，要记得更新下`README.md`哦

**Comment by wcySpring** [comment]
已经更新 但代码风格配置不同需要二次格式化一下

**Comment by QC2168** [comment]
嗯 我后续追加下lint

**Comment by wcySpring** [comment]
hello, 指定文章前缀 功能出发地点是文字是有顺序的，我想通过特定名字标识符用来，将文件按照顺序展示。如果我
**没有按照特定标识符排序如下**
![image](https://user-images.githubusercontent.com/128951289/236832671-ea3c3984-9636-4c49-89b1-fd3f214b0938.png)
但实际顺序我先颠倒过来因此我用了1. 2.来标记
![image](https://user-images.githubusercontent.com/128951289/236833005-c5589369-e51b-4abb-9b21-e5e083ccf745.png)

但我在菜单展示后的效果并不想展示 1. 2. 因为他仅仅作为一个我文章顺序标记
![image](https://user-images.githubusercontent.com/128951289/236833164-34a17669-badb-48ce-980c-28dde710a29d.png)

可能你错误理解我的pr 我的清除前缀是吧，提供特殊符号 例如. 前面的都清除掉，当然也可能是 @ # 任何符合 1#css 2#ass，变成 css ass 
~~~
function removePrefix(str, identifier) {
	const index = str.indexOf(identifier)
	if (index === -1) {
		// 如果字符串中不存在标识符，则返回原始字符串
		return str
	} else {
		// 否则返回标识符后面的所有字符
		return str.slice(index + identifier.length)
	}
}
~~~

**Comment by wcySpring** [comment]
如果有需要的话 我可以将我之前pr在提交回来，并不是现在的简单字符串替换为空，希望的是一个更加动态的
