### ISSUE TITLE
feat ：文章前缀 功能出发地点是文字是有顺序的 

### ISSUE THREAD

**Issue by wcySpring** [QC2168/vite-plugin-vitepress-auto-sidebar#7]
hello, 指定文章前缀 功能出发地点是文字是有顺序的，我想通过特定名字标识符用来，将文件按照顺序展示。如果我
**没有按照特定标识符排序如下**
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/0e7beea3-425a-442c-a678-583f2f25f022)

但实际顺序我先颠倒过来因此我用了1. 2.来标记
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/1c10bde2-881f-4596-bd1d-b804360d0088)

但我在菜单展示后的效果并不想展示 1. 2. 因为他仅仅作为一个我文章顺序标记
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/a91f5013-f12a-4944-8c55-6231f50519e1)

**可能错误理解我的pr 我的清除前缀是吧，提供特殊符号 例如. 前面的都清除掉，当然也可能是 @ # 任何符合 1#css 2#ass，变成 css ass**
~~~
function removePrefix(str, identifier) {
	const index = str.indexOf(identifier)
	if (index === -1) {
		// 如果字符串中不存在标识符，则返回原始字符串
		return str
	} else {
		// 否则返回标识符后面的所有字符
		return str.slice(index + identifier.length)
	}
}
~~~

**如果有需要的话 我可以将我之前pr在提交回来，并不是现在的简单字符串替换为空，希望的是一个更加动态的**

**Comment by QC2168** [comment]
@wcySpring 我明白了您的意思了，我把`deletePrefix`参数支持传入`regex`进行替换，这样子就可以解决您的问题了

举个例子：
如果您想将`1.css`、`2.sass`进行替换`css`、`sass`，可以传入`/\d+\./`进行替换

**Comment by wcySpring** [comment]
**这是我现在的文章结构**
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/cac75ab6-5e0f-4084-9abd-cbda584de37c)
**这是我的目录**
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/4dba41c3-cacb-49a4-bd98-d298e270898e)
**代码命名这些先忽略只是我的demo**
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/b374fee0-5d27-46f0-a6ae-6437bba62309)

你可以看到我的文件名有序号 但是我的目录没有序号，然后我还用了序号进行了排序

**Comment by wcySpring** [comment]
有的时候我觉得的这种大纲有顺序的目录是更多常态

**Comment by QC2168** [comment]
已经发布了`V1.4.1`版本，您试试看？

**Comment by wcySpring** [comment]
> 已经发布了`V1.4.1`版本，您试试看？
可能 npm 缓存还没更新现在我获取不到1.4.1 

这是我从现在项目暂时抽离出来的一个demo 在我自己的项目使用 我增加了 52 行的代码用来排序

![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/0588a2de-3f66-4307-877f-341ea6957fda)

**Comment by QC2168** [comment]
您用的是镜像站吗（如果是的话，可能是还没有同步到？），切换到`npmjs`官方的源尝试下

`yarn add vite-plugin-vitepress-auto-sidebar@latest`

**Comment by QC2168** [comment]
这个排序问题，我打算暴露一个`Api`，如果外部需要对侧边栏数据进行处理，可以直接在这个接口里面修改

**Comment by wcySpring** [comment]
> 这个排序问题，我打算暴露一个`Api`，如果外部需要对侧边栏数据进行处理，可以直接在这个接口里面修改

是的 我很同意你的想法，但现在1.4.1 版本去掉前缀也没达到预期效果 左侧是我自己的最小demo 展示，右侧是1.4.1 的展示
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/128951289/831cd0ca-6f50-43a1-91af-6651d3784867)

**Comment by wcySpring** [comment]
文章前缀是用来排序的最简单的标识，但是每个人习惯并不相同 有的人可能是 1、aa 2、bbb  或者 1.aa 2.bbb 最开始出发点是为了不让自定义前缀影响到菜单名字展示会显得很混乱 才增加了这个删除 删除也是删除自定义前缀

**Comment by QC2168** [comment]
我看了您的仓库，您需要把`deletePrefix: '.'`替换成`deletePrefix: /\d+\./`即可

**Comment by QC2168** [comment]
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/82024018/ef3dc209-7374-41c6-906e-f562285e1c6c)

**Comment by QC2168** [comment]
另外，collapsed默认值为false，可以不传递哦

**Comment by wcySpring** [comment]
> 另外，collapsed默认值为false，可以不传递哦

哈哈学到了，之前思维定式认为符号，没想到原来正则作为参数，很期待自定义排序的回调暴露出来，这样我就可以直接对接到现在的自动生成了

**Comment by QC2168** [comment]
如果您想对生成好了的侧边栏对象进行修改，可以使用`sideBarResolved`、`sideBarItemsResolved`钩子中执行~

**Comment by wcySpring** [comment]
哇太给力，是我现在在做vitepress 所需要的
