### ISSUE TITLE
如何排除文件夹里面的子目录

### ISSUE THREAD

**Issue by yecss** [QC2168/vite-plugin-vitepress-auto-sidebar#8]
您好，我想请问如何排除文件夹里面的指定的子目录
![image](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar/assets/32784471/ee076a23-bf5b-448f-95a1-561da9964204)
例如，图示我想排除JQuery文件夹里面的images文件夹

**Comment by QC2168** [comment]
@yecss  哈喽，你把插件更新到`1.5.1`版本以上，并配置下`ignoreList`这个选项
```javascript
plugins: [AutoSidebar({ignoreList:['images']})]
```

**Comment by yecss** [comment]
感谢作者大大的更新，问题已解决
